// Lexegen autogenerated definition file - do not edit!

enum {
    predef_pat_default = 0,
    pat_preproc_body,
    pat_comment,
    pat_preproc,
    pat_string,
    pat_id,
    pat_int,
    pat_real,
    pat_ws,
    pat_eof,
    pat_other,
};

enum {
    sc_initial = 0,
    sc_preproc,
};

struct CtxData {
    char* out_first = nullptr;
    char* out_last = nullptr;
    char* in_next = nullptr;
    char* in_last = nullptr;
    char* in_boundary = nullptr;
};
